# Dependencies
highlighter: pygments
markdown: redcarpet
redcarpet:
  extensions:
    - no_intra_emphasis
    - autolink
    - strikethrough
    - fenced_code_blocks
    - tables
gems:
  - jekyll-redirect-from


# Setup
title: Open Bioinformatics Foundation
baseurl: /
